# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean  app:assembleNotEmulatedDeviceDevtBeta")
    firebase_app_distribution(
      app: '1:236292085233:android:62e4ad69c351049f6ae050',
      firebase_cli_token: '1//0587tBnqvkFh_CgYIARAAGAUSNwF-L9Irjcn-51wvS6KSwn0nXRXCvvimo4CJ0_c_CFrHAxIc9TTpvM3-4K3Zhs76SfoX2uJUpJs'
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
